services:
  ygege:
    image: uwucode/ygege:latest
    container_name: ygege
    restart: unless-stopped 
    volumes:
      - ./ygege/sessions:/app/sessions
      - ./ygege/config.json:/app/config.json
    ports:
      - 8715:8715