name: Issue Report
description: Report a bug or malfunction in ygégé
labels: [bug, triage]
body:
  - type: markdown
    id: introduction
    attributes:
      value: |
        ### Thank you for helping improve ygégé!

        Before submitting a bug report, please make sure that:
        - You are using the latest stable version of ygégé.
        - Your issue has not already been reported on [GitHub Issues](https://github.com/UwUDev/ygege/issues).
        - This is not a usage or configuration question (use [Discussions](https://github.com/UwUDev/ygege/discussions) for that).

        Please fill out this form as precisely as possible to help us diagnose and fix the problem quickly.
  - type: checkboxes
    id: before-posting
    attributes:
      label: "Before posting, I have checked:"
      description: All conditions are **required**. Not following these may result in the issue being closed without comment.
      options:
        - label: This report is about a **bug** (not a question or feature request).
          required: true
        - label: This issue has not already been reported on [GitHub](https://github.com/UwUDev/ygege/issues).
          required: true
        - label: I am using the latest version of ygégé.
          required: true
        - label: I agree to follow the project's [Code of Conduct](CODE_OF_CONDUCT.md).
          required: true
        - label: This report concerns a single issue (one bug per ticket).
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Please describe the bug in detail (current behavior, error messages, logs, etc.).
      placeholder: |
        Example: After starting a search, the app crashes with the message "Network error". This happens every time, even after restarting.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      description: List the precise steps to reproduce the bug.
      placeholder: |
        1. Start ygégé with default configuration
        2. Open the web interface
        3. Perform a search for "Titanic"
        4. Observe the displayed error
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Observed behavior
      description: What is the current, incorrect or unexpected behavior?
      placeholder: |
        Example: The application shows "Network error" and returns no results.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What would be the correct, expected behavior?
      placeholder: |
        Example: The application should display the list of torrents matching the search.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: ygégé version
      description: Which version of ygégé are you using?
      options:
        - Latest stable release
        - Development version (master)
        - Older version (specify below)
    validations:
      required: true
  - type: input
    id: version-detail
    attributes:
      label: "Specify version number (if 'older version')"
      placeholder: |
        1.2.3
  - type: textarea
    id: environment
    attributes:
      label: Runtime environment
      description: |
        Please specify your environment:
        - **OS** (e.g. Debian 12, Ubuntu 24.04, Windows 11, macOS 14)
        - **Execution mode** (native binary, Docker, other)
        - **Architecture** (x86_64, ARM, etc.)
        - **Other relevant details**
      placeholder: |
        - OS: Debian 12
        - Mode: Docker
        - Architecture: x86_64
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: |
        Copy/paste relevant logs (errors, warnings) here or attach them if too large.
      render: shell
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Any other information useful to understand or reproduce the issue.
