name: Build and Push Multi-Arch Docker Image

on:
  release:
    types: [published]
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish Docker Images
    if: github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, '[skip ci]')
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.runner }}
    outputs:
      digest-amd64: ${{ steps.set_outputs.outputs.digest-amd64 }}
      digest-arm64: ${{ steps.set_outputs.outputs.digest-arm64 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # Must be 'uwudev'
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            uwudev/ygege
            ghcr.io/${{ env.OWNER_LC }}/ygege
          tags: |
            type=raw,value=master
            type=raw,value=sha-{{ sha }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            BUILD_VERSION=master
            BUILD_DATE=${{ github.event.repository.updated_at }}
          outputs: |
            type=image,push-by-digest=true,name=uwudev/ygege,push=true
            type=image,push-by-digest=true,name=ghcr.io/${{ env.OWNER_LC }}/ygege,push=true
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}
          provenance: false

      - name: Set outputs
        id: set_outputs
        run: |
          platform="${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}"
          echo "digest-${platform}=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  merge_and_push:
    name: Create and Push Multi-arch Manifest
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Create and push manifest
        run: |
          # Docker Hub manifest
          docker manifest create uwudev/ygege:master \
            --amend uwudev/ygege@${{ needs.build.outputs.digest-amd64 }} \
            --amend uwudev/ygege@${{ needs.build.outputs.digest-arm64 }}
          docker manifest push uwudev/ygege:master

          # GHCR manifest (fixed repo name)
          docker manifest create ghcr.io/${{ env.OWNER_LC }}/ygege:master \
            --amend ghcr.io/${{ env.OWNER_LC }}/ygege@${{ needs.build.outputs.digest-amd64 }} \
            --amend ghcr.io/${{ env.OWNER_LC }}/ygege@${{ needs.build.outputs.digest-arm64 }}
          docker manifest push ghcr.io/${{ env.OWNER_LC }}/ygege:master
